name: "CLA Assistant"
on:
  issue_comment:
    types: [created,edited, deleted]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: contains(github.event.comment.body, 'recheckcla') || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || github.event_name == 'pull_request'
        # Alpha Release
        uses: cla-assistant/github-action@v1.4.2-alpha
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-cla-document: 'https://github.com/gnosis/safe-react/blob/master/GNOSISCLA.md'
          branch: 'master'
          allowlist: lukasschor,rmeissner,apanizo,germartinez,fernandomg,Agupane,nicosampler,matextrem,gabitoesmiapodo,davidalbela,alongoni,Uxio0,dasanra,miguelmota,francovenica,tschubotz,pcowgill,luarx,giacomolicari,gnosis-info,bot*
          empty-commit-flag: false
          blockchain-storage-flag: false
